# Generated by Django 5.2.6 on 2025-09-16 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("diaria_base", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="PrecoDinamico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("concluida", "Concluída"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "preco_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("ano", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("alugado", "Alugado"),
                            ("manutencao", "Em manutenção"),
                        ],
                        default="disponivel",
                        max_length=20,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veiculos",
                        to="autorent.categoriaveiculo",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.AddField(
            model_name="reserva",
            name="veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="autorent.veiculo",
            ),
        ),
        migrations.AddField(
            model_name="precodinamico",
            name="veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precos_dinamicos",
                to="autorent.veiculo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="precodinamico",
            unique_together={("veiculo", "data")},
        ),
    ]
