# Generated by Django 5.2.6 on 2025-09-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autorent", "0003_alter_reserva_usuario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="precodinamico",
            options={"ordering": ["data"]},
        ),
        migrations.AlterModelOptions(
            name="reserva",
            options={"ordering": ["-criado_em"]},
        ),
    ]
