# Generated by Django 5.2.6 on 2025-09-17 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorent", "0004_alter_precodinamico_options_alter_reserva_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaveiculo",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="categoriaveiculo",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2025, 9, 17, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="precodinamico",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="precodinamico",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2025, 9, 17, 0, 0)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reserva",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 9, 17, 19, 19, 19, 370880, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
