# Generated by Django 5.2.6 on 2025-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorent", "0005_categoriaveiculo_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaveiculo",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="categoriaveiculo",
            name="deletado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="precodinamico",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="precodinamico",
            name="deletado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="deletado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="veiculo",
            name="deletado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
