# Generated by Django 5.2.6 on 2025-09-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('cor', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('ECONOMICO', 'Econômico'), ('COMPACTO', 'Compacto'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('LUXO', 'Luxo')], max_length=10)),
                ('tipo_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('FLEX', 'Flex'), ('DIESEL', 'Diesel')], max_length=10)),
                ('transmissao', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], max_length=10)),
                ('assentos', models.IntegerField(default=5)),
                ('portas', models.IntegerField(default=4)),
                ('ar_condicionado', models.BooleanField(default=True)),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ALUGADO', 'Alugado'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=15)),
                ('localizacao', models.CharField(default='Matriz', max_length=100)),
                ('quilometragem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['marca', 'modelo'],
            },
        ),
    ]
