# Generated by Django 5.2.6 on 2025-09-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_dias', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('ATIVA', 'Ativa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15)),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('FALHOU', 'Falhou'), ('REEMBOLSADO', 'Reembolsado')], default='PENDENTE', max_length=15)),
                ('local_retirada', models.CharField(max_length=100)),
                ('local_devolucao', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('km_inicial', models.IntegerField(blank=True, null=True)),
                ('km_final', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('DINHEIRO', 'Dinheiro')], max_length=20)),
                ('id_transacao', models.CharField(blank=True, max_length=100)),
                ('resposta_gateway', models.JSONField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
