# Generated by Django 5.2.6 on 2025-09-15 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alugueis', '0001_initial'),
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='veiculos.veiculo'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='locacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='alugueis.locacao'),
        ),
    ]
